version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:16.11.0-ce.0
    container_name: gitlab
    restart: always
#    hostname: 'gitlab'
#    environment:
#      GITLAB_OMNIBUS_CONFIG: |
#        # Add any other gitlab.rb configuration here, each on its own line
#        external_url 'https://gitlab.example.com'
    ports:
      - '8080:80'
      - '4343:443'
      - '2222:22'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    shm_size: '256m'
